language: haskell
ghc:
  # - 8.0
  - 7

install:
  cabal sandbox init &&
  cabal install --only-dependencies --enable-tests

script: 
  cabal configure --enable-tests && cabal build && 
  cabal test Lexer && cabal test Parser && cabal test Evaluator && cabal test UnitParsing
  # cabal test # Need to fix the build, so it can run all the tests

# branches:
#   only:
#     - master
#     - stable